version: "3.1"
language: pt

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 100
  fallback_threshold: 0.4
  fallback_action_name: "utter_fallback"

policies:
- name: MemoizationPolicy
- name: RulePolicy
assistant_id: 20260318-142950-colorful-ident
